### PR TITLE
feat: alchemist incarnation

### PR DESCRIPTION
**Pull request by nicolasfara**

### CODE REVIEW

**Comment by DanySK** [comment]
How is the CI not running?

**Comment by nicolasfara** [comment]
> How is the CI not running?

Because the last commit addresses a file that does not trigger the CI...

**Comment by DanySK** [comment]
But it should work the other way around: run unless only files specified as non-triggering are modified

**Comment by nicolasfara** [comment]
> But it should work the other way around: run unless only files specified as non-triggering are modified

Yes, and I think that is what happened. The (non)-last commit that addresses the file that triggers a release has been concluded. In the meantime, I have modified a non-triggering file and the CI in the PR was not triggered and a dangling state was reported since the `success` status check is required to merge the PR.
It isn't an our-side problem or a wrong CI configuration, I suppose.

**Pull request merged**
